import type { AdrRecord, AdrRelationType } from '../generated/adr'

export interface GraphEdge {
  from: string
  to: string
  kind: AdrRelationType
}

export function buildGraph(records: AdrRecord[]): { nodes: AdrRecord[]; edges: GraphEdge[] } {
  const edges: GraphEdge[] = []
  const seen = new Set<string>()
  for (const r of records) {
    for (const rel of r.relations) {
      const key = `${r.id}\u2192${rel.targetId}:${rel.type}`
      if (seen.has(key)) continue
      seen.add(key)
      edges.push({ from: r.id, to: rel.targetId, kind: rel.type })
    }
  }
  return { nodes: records, edges }
}

/** "0007 → fue reemplazada por". Clave por id de ADR. */
export function supersededByMap(records: AdrRecord[]): Record<string, string[]> {
  const map: Record<string, string[]> = {}
  for (const r of records) {
    for (const rel of r.relations) {
      if (rel.type !== 'supersedes') continue
      map[rel.targetId] ??= []
      map[rel.targetId].push(r.id)
    }
  }
  return map
}

/** Layout por capas: columna = posición en la cadena de superseding/dependencia, fila = fecha. */
export function layeredLayout(records: AdrRecord[], edges: GraphEdge[]): Record<string, { x: number; y: number }> {
  const ids = new Set(records.map((r) => r.id))
  const byId = new Map(records.map((r) => [r.id, r]))
  const rank: Record<string, number> = {}
  for (const r of records) rank[r.id] = 0

  // relajación monotónica: el origen de un supersedes/depends_on va una columna después del destino
  const relevant = edges.filter((e) => {
    if (e.kind !== 'supersedes' && e.kind !== 'depends_on') return false
    return ids.has(e.from) && ids.has(e.to)
  })
  for (let i = 0; i <= records.length; i++) {
    let changed = false
    for (const e of relevant) {
      if (rank[e.from]! < rank[e.to]! + 1) {
        rank[e.from] = rank[e.to]! + 1
        changed = true
      }
    }
    if (!changed) break
  }
  const min = Math.min(...Object.values(rank))
  for (const id of Object.keys(rank)) rank[id] -= min

  const columns: Record<number, string[]> = {}
  for (const r of records) {
    const c = rank[r.id] ?? 0
    ;(columns[c] ??= []).push(r.id)
  }
  const order = Object.keys(columns).map(Number).sort((a, b) => a - b)

  const out: Record<string, { x: number; y: number }> = {}
  for (const c of order) {
    const list = (columns[c] ?? []).slice().sort((a, b) => {
      const da = byId.get(a)?.date ?? ''
      const db = byId.get(b)?.date ?? ''
      return da.localeCompare(db)
    })
    list.forEach((id, i) => {
      out[id] = { x: 60 + order.indexOf(c) * 340, y: 40 + i * 220 }
    })
  }
  return out
}

// ---------- Export Mermaid ----------

/** Título corto y sanitizado para volcar en un label de Mermaid (sin comillas/backticks). */
export function cleanMermaidLabel(text: string): string {
  return String(text ?? '')
    .replace(/["`\r\n]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
}

function statusOf(rec: AdrRecord) {
  return (
    rec.statusMeta?.find((s) => s.key === rec.status) ??
    DEFAULT_STATUS[rec.status] ?? {
      key: rec.status,
      emoji: '•',
      label: rec.status,
    }
  )
}

/** Fallback cuando el record viene sin statusMeta (ej. desde el parser en node). */
const DEFAULT_STATUS: Record<string, { emoji: string; label: string }> = {
  proposed: { emoji: '🟡', label: 'Proposed' },
  accepted: { emoji: '✅', label: 'Accepted' },
  rejected: { emoji: '❌', label: 'Rejected' },
  deprecated: { emoji: '⚠️', label: 'Deprecated' },
  superseded: { emoji: '🔁', label: 'Superseded' },
}

/**
 * Genera un diagrama Mermaid (flowchart LR) desde los ADRs: cada nodo es un ADR
 * con su status emoji + id, y las relaciones son flechas dirigidas etiquetadas.
 * Compatible con mermaid.live / GitHub README (`.mmd`).
 */
export function toMermaid(records: AdrRecord[]): string {
  const meta = new Map(records.map((r) => [r.id, r]))
  const { edges } = buildGraph(records)
  const out: string[] = []
  out.push('%% Generated by repoDocs ADR Premium — architecture decision records')
  out.push('flowchart LR')
  for (const r of records) {
    const status = statusOf(r)
    const label = `${status.emoji} ${r.id} · ${cleanMermaidLabel(r.title)}`.replace(/\[|\]/g, '(')
    out.push(`  n${r.id}["${label}"]`)
  }
  for (const e of edges) {
    if (!meta.has(e.from) || !meta.has(e.to)) continue
    out.push(`  n${e.from} -->|${e.kind}| n${e.to}`)
  }
  return out.join('\n')
}